### PR TITLE
add issue and PR templates

### PR DESCRIPTION
**Pull request by rjcorb**
This PR adds issue and PR templates as per issue #66

### CODE REVIEW

**Review by jharenza — COMMENTED** [review]
I should have put this into the ticket - can you use these, as revelant, instead, since this is geared toward tool and development of the tool?

https://github.com/d3b-center/annoFuse/tree/master/.github

**Comment by rjcorb** [comment]
> I should have put this into the ticket - can you use these, as revelant, instead, since this is geared toward tool and development of the tool?
> 
> https://github.com/d3b-center/annoFuse/tree/master/.github

@jharenza just replaced

**Review by naqvia — APPROVED** [review]
Looks good to me!

**Comment by jharenza** [comment]
@rjcorb can you update the text on these to be autogvp specific- seeing annoFuse info in here and also be sure the asks make sense for this repo? Thanks

**Review by jharenza — CHANGES_REQUESTED** [review]
See comments

**Review by jharenza — APPROVED** [review]

**Comment by jharenza** [comment]
Closes #66

**Pull request merged**
