### PR TITLE
Requesting to change files for testing input

### PR DESCRIPTION
**Pull request by jungkim2**
adding full package of input test files

### CODE REVIEW

**Review by jharenza — COMMENTED** [review]
@jungkim2 this looks good, but can you also then delete the old ones? Thanks!

**Comment by jungkim2** [comment]
Done!

**Review by jharenza — COMMENTED** [review]
ok sorry one more thing - can you update the readme with these new filenames for the autogvp run command?

**Comment by jungkim2** [comment]
I have made edits. Also found that the small option label needs to be changed.

**Review by jharenza — APPROVED** [review]

**Review by jharenza — CHANGES_REQUESTED** [review]
looks like there is a merge conflict - actually you have the old readme in here. Can you update on the recent readme, or go to your main branch, pull all updates, then go to this branch and do a `git merge main` to get the current readme? the current readme is in the root- what you had updated no longer exists, but i don't think i can help modify the branch

**Comment by jungkim2** [comment]
Updated and requesting it again

**Review by jharenza — APPROVED** [review]

**Pull request merged**
