### PR TITLE
Create comprehensive AutoGVP output 

### PR DESCRIPTION
**Pull request by rjcorb**
#### What feature is being added or bug is being addressed?

This PR modifies `01-annotate_variants_CAVATICA_input.R` and `01-annotate_variants_custom_input.R` scripts to retain additional columns from multianno, intervar, and autopvs1 files in AutoGVP output. 

#### What was your approach?

Modified column filtering of multianno and intervar files 

#### What GitHub issue does your pull request address?

#81 #103 

#### Which areas should receive a particularly close look?

Please review updated code for logic 

#### Is there anything that you want to discuss further?

No

#### Documentation Checklist

- [X] The function has examples to showcase the usage

### CODE REVIEW

**Comment by jungkim2** [comment]
The ones that doesn't have ClinVar call, all fields are getting NA 

`<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/kimjua/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/kimjua/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



CHROM | POS | ID | REF | ALT | final_call | Reasoning_for_call | Stars | ClinVar_ClinicalSignificance | Intervar_evidence | AF | AF_popmax | AF_male
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
NA | NA | NA | NA | NA | Uncertain_significance | InterVar | NA | NA | InterVar: Uncertain significance PVS1=0 PS=[0, 0, 0, 0, 0] PM=[0, 1, 0,   0, 0, 0, 0] PP=[0, 0, 0, 0, 0, 0] BA1=0 BS=[0, 0, 0, 0, 0] BP=[0, 0, 0, 0, 0,   0, 0, 0] | . | . | .
7 | 93131118 | 1216669 | G | A | Likely_benign | ClinVar | 1 | Likely benign | InterVar: Uncertain significance PVS1=0 PS=[0, 0, 0, 0, 0] PM=[0, 0, 0,   0, 0, 0, 0] PP=[0, 0, 0, 0, 0, 0] BA1=0 BS=[1, 0, 0, 0, 0] BP=[0, 0, 0, 0, 0,   0, 0, 0] | 0.0183 | 0.0831 | 0.0189
NA | NA | NA | NA | NA | Uncertain_significance | InterVar | NA | NA | InterVar: Uncertain significance PVS1=0 PS=[0, 0, 0, 0, 0] PM=[0, 1, 0,   0, 0, 0, 0] PP=[0, 0, 0, 0, 0, 0] BA1=0 BS=[0, 0, 0, 0, 0] BP=[0, 0, 0, 0, 0,   0, 0, 0] | . | . | .
NA | NA | NA | NA | NA | Uncertain_significance | InterVar | NA | NA | InterVar: Uncertain significance PVS1=0 PS=[0, 0, 0, 0, 0] PM=[0, 1, 0,   0, 0, 0, 0] PP=[0, 0, 0, 0, 0, 0] BA1=0 BS=[0, 0, 0, 0, 0] BP=[0, 0, 0, 0, 0,   0, 0, 0] | . | . | .



</body>

</html>
`

**Comment by rjcorb** [comment]
@jungkim2 that issue should be resolved now

**Review by jungkim2 — APPROVED** [review]
tested

**Review by naqvia — APPROVED** [review]
Runs and prints desired output!

**Pull request merged**
