### PR TITLE
update select-clinvar-submissions.R to only consider P,LP,B,LB,VUS submissions

### LINKED ISSUE #222: Remove "association, risk factor" submissions when resolving conflicting interpretations
#### Briefly describe the feature and provide meaningful references

Update `select-clinvar-submissions.R` script to remove submissions that are not P,LP,B,LB, or US prior to resolving conflicts.

### PR DESCRIPTION
**Pull request by rjcorb**
#### What feature is being added or bug is being addressed?

Closes #222. This PR updates `select-clinvar-submissions.R` to retain only P,LP,B,LB, and VUS submissions when attempting to resolve ClinVar variants with conflicting interpretation. 

#### What was your approach?

Removed all submissions for which `ClinicalSignificance` did not equal one of the above values. 

#### What GitHub issue does your pull request address?

#222. 

#### Which areas should receive a particularly close look?

Please re-run `select-clinvar-submissions.R` and ensure that `ClinicalSignificance` is only equal to P,LP,B,LB, or US in output. 

```
Rscript scripts/select-clinVar-submissions.R --variant_summary data/variant_summary.txt.gz --submission_summary data/submission_summary.txt.gz --outdir results --conceptID_list data/clinvar_all_disease_concept_ids.txt --conflict_res "latest"
```

#### Is there anything that you want to discuss further?

I will submit a separate PR to make sure that variants with "unconventional" ClinVar clinical significance (see [Variant ID 822](https://www.ncbi.nlm.nih.gov/clinvar/variation/822/?oq=822&m=NM_000038.6(APC):c.3920T%3EA%20(p.Ile1307Lys) as an example) are resolved by ClinVar during AutoGVP run. 

#### Documentation Checklist

- [X] The function has examples to showcase the usage

### CODE REVIEW

**Comment by rjcorb** [comment]
@rebkau I think this will resolve the issue with the APC variant. Can you run AutoGVP on that sample and see if the correct call is made (LP, ClinVar)?

**Review by jharenza — COMMENTED** [review]
Runs without issue now - will let @rebkau confirm the results are as expected! @rjcorb can you pop a clarifying instruction for the optional download data script in the readme? thanks!

**Review by rebkau — APPROVED** [review]
@rjcorb This runs for me now.  The new calls are as expected.

**Comment by naqvia** [comment]
Works for me as well!

**Pull request merged**
