### PR TITLE
Update germline-pathogenecity_flow.png

### PR DESCRIPTION
**Pull request by jharenza**
#### What feature is being added or bug is being addressed?
Updating the main figure to include disease decisions

#### Documentation Checklist

- [ ] The function has examples to showcase the usage 
- [ ] Added a vignette

### CODE REVIEW

**Review by rjcorb — APPROVED** [review]
looks good!

**Review by jungkim2 — CHANGES_REQUESTED** [review]
For box for "Calls associated with a known disease" (yes), we should make it clear that majority call is only for those with ONLY submissions associated with those diseases. 
Also for those that we resolve ClinVar, maybe it is worth to say "Resolved ClinVar Classification"
For Modified InterVar classification, we can note on figure legend or in the figure, we can mention, applied autoPVS1 and removal of PP5/BP6

**Comment by jharenza** [comment]
@jungkim2 would you be able to update the figure in biorender? I sent the link in slack.

**Comment by jungkim2** [comment]
Yup! I can do that

**Comment by jharenza** [comment]
@jungkim2 made a few tweaks - let me know how this looks

**Review by jungkim2 — APPROVED** [review]

**Pull request merged**
