### PR TITLE
Add columns to abridged output

### PR DESCRIPTION
**Pull request by rjcorb**
This PR addresses issue #52 by modifying `01-annotate_variants_CAVATICA_input.R` and `01-annotate_variants_custom_input.R` scripts to retain the following columns in abridged output: 

- `Gene.refGene` from multianno file. This columns lists all genes overlapping variant 
- `consequence` and `criterion` from autopvs1 file
- `CLNSIG` and `CLNREVSTAT` from multianno file
- `Reasoning_for_call` indicating whether call was made from ClinVar or Intervar

`dplyr::select(any_of())` was used to select data frame columns, so the script should be robust in cases where some of these columns may not be found in input files. 

Please review modifications made to each script, run scripts on test files, and review output.

### CODE REVIEW

**Comment by naqvia** [comment]
I am testing the CAVATICA workflow, and I don't see the columns printed out. I do not the `Reasoning_for_call` (that chunk of code is missing?). I also do not see the `AutoPVS1` columns printed.

**Comment by naqvia** [comment]
I have tried running with the custom script with the following statement: 
`Rscript 01-annotate_variants_custom_input.R --vcf input/test_VEP.vcf --multianno input/test_VEP.vcf.hg38_multianno.txt --intervar input/test_VEP.hg38_multianno.txt.intervar --autopvs1 input/test_autopvs1.txt --clinvar input/clinvar.vcf.gz --output test_custom --variant_summary input/variant_summary.txt --submission_summary input/submission_summary.txt`

I get the following columns (grepped first 2 lines):

```
vcf_id	Ref.Gene	Func.refGene	ExonicFunc.refGene	AAChange.refGene	Stars	Intervar_evidence	intervar_adjusted_call	ID	final_call	Reasoning_for_call
1-100990636-TA-T	DPH5	intronic	.	.	NA	InterVar: Uncertain significance PVS1=0 PS=[0, 0, 0, 0, 0] PM=[0, 0, 0, 0, 0, 0, 0] PP=[0, 0, 0, 0, 0, 0] BA1=0 BS=[0, 0, 0, 0, 0] BP=[0, 0, 0, 0, 0, 0, 0, 0]	No	NA	Uncertain_significance	Intervar
```
The autopvs1 columns are not reported, but in thie case the `Reasoning_for_call` is...

**Comment by rjcorb** [comment]
@naqvia I've edited both custom and cavatica scripts, those columns should be retained in final output now

**Comment by naqvia** [comment]
Great. So both run and do as expected, but I had to add chunk of code related to `Reasoning_for_call` that I borrowed directly from the custom workflow to the CAVATICA script; looks like you had just missed this portion. All desired columns are now are reported. Can you do one final check and then we could merge!

**Review by naqvia — APPROVED** [review]
works as expected after adding that chunk of code.

**Pull request merged**
